[package]
name = "nail_website_server"
version = "0.1.0"
edition = "2021"

[dependencies]
nail = { path = ".." }
axum = "0.7"
dashmap = "6.1.0"
futures = "0.3"
rayon = "1.10.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
