[package]
name = "nail_website_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
nail = { path = ".." }
dashmap = "6"
rayon = "1.5"
futures = "0.3"
axum = "0.7"
