[package]
name = "nail_website_server"
version = "0.1.0"
edition = "2021"

[dependencies]
nail = { path = "..", features = ["html"] }
axum = { version = "0.7", features = ["ws"] }
chrono = "0.4"
dashmap = { version = "6.1.0", features = ["serde"] }
futures = "0.3"
pulldown-cmark = "0.9"
rayon = "1.10.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.5", features = ["fs"] }
urlencoding = "2.1"

[profile.release]
lto = "thin"
codegen-units = 1
