[package]
name = "Nail"
version = "0.0.1"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
ratatui = { version = "0.28.1", features = ["all-widgets", "crossterm"] }
rayon = "1.10.0"
regex = "1.10.6"

