#!/usr/bin/env bash
# Publishes a Nail release. Run from your machine, after build_bundle.sh.
#
#   ./deploy/releases.sh bundle/nail-0.1.0-linux-x86_64.tar.xz
#   ./deploy/releases.sh --withdraw 0.1.0        # unpublish one
#   ./deploy/releases.sh --refresh               # rebuild the download page's list
#
# Uploads the finished bundle to the droplet and points /versions/latest at it.
# The droplet serves the file itself: what users download is a compiled
# artifact, not a git tag, so there is nothing a source host could serve that
# would match a release anyway.
#
# Caddy serves it straight off disk, so the bytes never pass through the
# website process and its memory limit is irrelevant. A bundle is roughly one
# to two gigabytes, against ~10GB of droplet disk and 500GB/month of transfer,
# which is one or two versions live at a time.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

APP_PORT=8080
SRV=/srv/nail-releases

env_val() {
	[[ -f .env ]] || return 0
	grep -E "^$1=" .env | tail -1 | cut -d= -f2- | sed 's/^"\(.*\)"$/\1/'
}

HOST="${DEPLOY_HOST:-$(env_val DEPLOY_HOST)}"
RELEASE_DOMAIN="${RELEASE_DOMAIN:-$(env_val RELEASE_DOMAIN)}"
[[ -n "$HOST" ]] || { echo "set DEPLOY_HOST in .env" >&2; exit 1; }
[[ -n "$RELEASE_DOMAIN" ]] || { echo "set RELEASE_DOMAIN in .env (the hostname nail fetches releases from)" >&2; exit 1; }

SSH=(ssh -o StrictHostKeyChecking=accept-new)
SCP=(scp -o StrictHostKeyChecking=accept-new)
DEPLOY_PASSWORD="${DEPLOY_PASSWORD:-$(env_val DEPLOY_PASSWORD)}"
if [[ -n "$DEPLOY_PASSWORD" ]]; then
	command -v sshpass >/dev/null || { echo "DEPLOY_PASSWORD is set but sshpass is not installed" >&2; exit 1; }
	export SSHPASS="$DEPLOY_PASSWORD"
	SSH=(sshpass -e "${SSH[@]}")
	SCP=(sshpass -e "${SCP[@]}")
fi

# A list for the download page to read. The website is sandboxed to /srv/nail
# and cannot see the release directory, so the list is written where it can.
#
# This is for people, not for the launcher. It names a version in a URL and that
# is the whole protocol: if it ever started reading a list, the list would
# become something that has to stay correct forever, which is exactly what was
# avoided by not having one.
write_release_list() {
	"${SSH[@]}" "$HOST" "bash -s" <<EOF
set -euo pipefail
{
	for dir in $SRV/versions/*/; do
		[ -f "\$dir/x86_64-linux" ] || continue
		v="\$(basename "\$dir")"
		printf '%s\t%s\t%s\n' "\$v" "\$(stat -c%s "\$dir/x86_64-linux")" "\$(stat -c%y "\$dir/x86_64-linux" | cut -d' ' -f1)"
	done
} | sort -Vr > /srv/nail/releases.tsv
chown nail:nail /srv/nail/releases.tsv 2>/dev/null || true
systemctl restart nail 2>/dev/null || true
EOF
	echo "wrote the release list"
}

write_caddy_fragment() {
# Caddy fragment. It replaces the one add-app.sh wrote for this host, since
# Caddy allows one block per hostname, and proxies the website as its fallback.
"${SSH[@]}" "$HOST" "bash -s" <<EOF
set -euo pipefail
mkdir -p $SRV
chmod 755 $SRV
cat > /etc/caddy/sites.d/nail.caddy <<'CADDY'
# Generated by deploy/releases.sh. Serves Nail releases and the website.
$RELEASE_DOMAIN {
	handle_path /versions/* {
		root * $SRV/versions
		file_server
	}

	handle_path /nail/* {
		root * $SRV/nail
		file_server
	}

	handle_path /desktop/* {
		root * $SRV/desktop
		file_server
	}

	handle {
		encode zstd gzip
		reverse_proxy 127.0.0.1:$APP_PORT
	}
}

www.$RELEASE_DOMAIN {
	redir https://$RELEASE_DOMAIN{uri} permanent
}
CADDY
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null
systemctl reload caddy || systemctl restart caddy
EOF
	echo "wrote the caddy fragment"
}

# Regenerate the download page's list and the routes, without republishing.
if [[ "${1:-}" == "--refresh" ]]; then
	# The launcher is version independent, so it can be replaced without
	# republishing a release. This is also what stops `curl | sudo sh` handing
	# someone an older launcher than the one that is current.
	if [[ -x target/release/nail-launcher ]]; then
		"${SSH[@]}" "$HOST" "mkdir -p $SRV/nail"
		"${SCP[@]}" target/release/nail-launcher "$HOST:$SRV/nail/.incoming"
		"${SSH[@]}" "$HOST" "chmod 755 $SRV/nail/.incoming && mv $SRV/nail/.incoming $SRV/nail/x86_64-linux"
		echo "uploaded the launcher"
	fi
	"${SSH[@]}" "$HOST" "mkdir -p $SRV/desktop"
	for file in nail.desktop nail.xml nail.svg; do
		"${SCP[@]}" "bundle/desktop/$file" "$HOST:$SRV/desktop/$file"
	done
	write_release_list
	write_caddy_fragment
	exit 0
fi

# Unpublishing is deleting the file. Alpha releases are allowed to go away.
if [[ "${1:-}" == "--withdraw" ]]; then
	VERSION="${2:?usage: $0 --withdraw <version>}"
	"${SSH[@]}" "$HOST" "rm -rf $SRV/versions/$VERSION"
	echo "withdrew $VERSION"
	exit 0
fi

TARBALL="${1:?usage: $0 <bundle.tar.xz>}"
[[ -f "$TARBALL" ]] || { echo "no such file: $TARBALL" >&2; exit 1; }

# The version is the bundle's own name, so there is no way to publish one
# release under another's number.
VERSION="$(basename "$TARBALL" | sed -n 's/^nail-\(.*\)-linux-x86_64\.tar\.xz$/\1/p')"
[[ -n "$VERSION" ]] || { echo "cannot read a version out of $(basename "$TARBALL")" >&2; exit 1; }

echo "== publishing $VERSION ($(du -h "$TARBALL" | cut -f1)) =="

"${SSH[@]}" "$HOST" "mkdir -p $SRV/versions/$VERSION $SRV/nail"

# Upload beside the final name and move it into place, so a launcher that asks
# mid-upload gets a 404 rather than half a bundle.
"${SCP[@]}" "$TARBALL" "$HOST:$SRV/versions/$VERSION/.incoming"
"${SSH[@]}" "$HOST" "mv $SRV/versions/$VERSION/.incoming $SRV/versions/$VERSION/x86_64-linux"

# The desktop files the installer fetches: what makes a .nail file get an icon
# and an "Open with Nail" entry. Small, and served from the same place as
# the launcher, so the web installer needs nothing but this host.
"${SSH[@]}" "$HOST" "mkdir -p $SRV/desktop"
for file in nail.desktop nail.xml nail.svg; do
	"${SCP[@]}" "bundle/desktop/$file" "$HOST:$SRV/desktop/$file"
done
echo "uploaded desktop integration"

if [[ -x target/release/nail-launcher ]]; then
	"${SCP[@]}" target/release/nail-launcher "$HOST:$SRV/nail/.incoming"
	"${SSH[@]}" "$HOST" "chmod 755 $SRV/nail/.incoming && mv $SRV/nail/.incoming $SRV/nail/x86_64-linux"
	echo "uploaded the launcher"
fi

"${SSH[@]}" "$HOST" "printf '%s\n' '$VERSION' > $SRV/versions/latest"

write_release_list

write_caddy_fragment

echo
echo "published:"
echo "  https://$RELEASE_DOMAIN/versions/latest"
echo "  https://$RELEASE_DOMAIN/versions/$VERSION/x86_64-linux"
echo "  https://$RELEASE_DOMAIN/nail/x86_64-linux"
